// Code generated by mockery v1.0.0
package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import tracker "github.com/darren-west/marathon/tracker"

// LocationServiceServer is an autogenerated mock type for the LocationServiceServer type
type LocationServiceServer struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *LocationServiceServer) Create(_a0 context.Context, _a1 *tracker.CreateRequest) (*tracker.CreateResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *tracker.CreateResponse
	if rf, ok := ret.Get(0).(func(context.Context, *tracker.CreateRequest) *tracker.CreateResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tracker.CreateResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *tracker.CreateRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
